spring.application.name=eshop

spring.datasource.url=jdbc:postgresql://localhost:5432/eshop_db
spring.datasource.username=postgres
spring.datasource.password=qaz159
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JPA \u8A2D\u5B9A
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Thymeleaf 
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

server.port=8080
server.servlet.context-path=/eshop

spring.jpa.properties.hibernate.jdbc.time_zone=UTC